export const cardData = [
  {
    id: 1,
    title: "Parent's Orientation",
    img: "/img1.jpg",
    date: "10 Sep, 2022",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 2,
    title: "Open Registration",
    img: "/img2.jpg",
    date: "23 Jan, 2025",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 3,
    title: "Students Disipline",
    img: "/img3.jpg",
    date: "01 Mar, 2021",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 4,
    title: "Fun Activities",
    img: "/img4.jpg",
    date: "25 Apr, 2022",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 5,
    title: "Halloween Event",
    img: "/Halloween.png",
    date: "22 Sep, 2024",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 6,
    title: "Classroom Environment",
    img: "/counter_bg.jpeg",
    date: "14 Feb, 2022",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 7,
    title: "Parent's Orientation",
    img: "/img1.jpg",
    date: "10 Sep, 2022",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 8,
    title: "Open Registration",
    img: "/img2.jpg",
    date: "23 Jan, 2025",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 9,
    title: "Students Disipline",
    img: "/img3.jpg",
    date: "01 Mar, 2021",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 10,
    title: "Fun Activities",
    img: "/img4.jpg",
    date: "25 Apr, 2022",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 11,
    title: "Halloween Event",
    img: "/Halloween.png",
    date: "22 Sep, 2024",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
  {
    id: 12,
    title: "Classroom Environment",
    img: "/counter_bg.jpeg",
    date: "14 Feb, 2022",
    location: "Forest Hill International School",
    time: "8am-11am",
  },
];
